# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Timo Bakx"
email: "timobakx@gmail.com"
description: "This is a blog (mostly) about development in PHP and Symfony."
baseurl: ""
url: "https://timobakx.dev"

github:
    username: "TimoBakx"
    owner_name: "Timo"
    owner_url: "https://github.com/TimoBakx/"

twitter:
    username: "TimoBakx"

mastodon:
    uri: "https://phpc.social/@timobakx"

header_page_refs:
    - "about"

# Build settings
markdown: "kramdown"
theme: "jekyll-theme-cayman"
plugins:
    - "jekyll-feed"

feed:
    excerpt_only: true

people:
    - ref: iulia
      fullName: Iulia Stana
    - ref: bart
      fullName: Bart van Raaij
    - ref: robin
      fullName: Robin Keet
      website: https://keet.me
    - ref: COil
      fullName: COil
    - ref: alan_poulain
      fullName: Alan Poulain
      website: https://github.com/alanpoulain

exclude:
    - Gemfile
    - Gemfile.lock
    - _site
    - .idea
    - samples
    - bin
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
